server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/microservices
    username: root
    password: Bademiaa@14
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#      properties:
#        hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect

  application:             # after applying the config file then its an optional to use it but we need to give name on that config server in git hub
    name: User Service


# here we need to import the config server in which port it is running
  config:
    import: http://localhost:8086
    #spring.config.import = configserver:http://localhost:8086

# ------------------- wer dont need to write this because we fetch the data from github serer
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8084/eureka
